# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvheg8cXq11he-H5Biz_3OZl8e7vZa-4
"""

import numpy as np
from sklearn import linear_model
import pandas as pd

df=pd.read_csv(r"C:\Users\aksha\Desktop\well predictor\newdataset.csv")
df

from sklearn.tree import DecisionTreeRegressor
reg=DecisionTreeRegressor()

X=df[['Latitude','Longitude']]
Y=df[['Apr-23.1','May-23.1','Nov-23.1']]

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=42)

reg.fit(X_train,Y_train)

input = np.array([[15,80]])

reg.predict(input)

from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
Y_pred=reg.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
print(mse)

import pickle
with open('Rainfall.pkl','wb') as f:
  pickle.dump(reg,f)